export const ActionTypes = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_TAGS: 'SET_TAGS',
    SET_DOCUMENTS: 'SET_DOCUMENTS',
    SET_DOCUMENTS_PAGINATION: 'SET_DOCUMENTS_PAGINATION',
    REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',
    EDIT_DOCUMENT: 'EDIT_DOCUMENT',
};
