export const ActionTypes = {
    // Auth
    SET_USER: 'SET_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_DOCUMENTS: 'LOGOUT_DOCUMENTS',
    LOGOUT_TAGS: 'LOGOUT_TAGS',

    // Dokumenty
    SET_DOCUMENTS: 'SET_DOCUMENTS',
    SET_DOCUMENTS_PAGINATION: 'SET_DOCUMENTS_PAGINATION',
    EDIT_DOCUMENT: 'EDIT_DOCUMENT',
    REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',

    // Tagy
    SET_TAGS: 'SET_TAGS',
};
